name: games_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  get_it: ^7.6.7
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.5
  flame: ^1.35.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3   # ← App Icon package

# ==========================================
# APP ICON CONFIGURATION
# ==========================================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/gamehub.png"   # ← Aapki image
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

# ==========================================
# FLUTTER ASSETS
# ==========================================
flutter:
  uses-material-design: true

  assets:
    - assets/images/       # ← Saari images folder se
    - assets/questions.json